### ISSUE TITLE
<실험과정>

### ISSUE THREAD

**Issue by June222** [YeoJiSu/Avoiding_Obstacles_Robot#10]
11/30
`GPIOC->BSRR = GPIO_Pin_9;` : 

=>2번 릴레이 모듈에 신호가 들어올 경우( 9번 핀 활성화 ) 왼쪽 바퀴가 앞으로 간다.

`GPIOC->BSRR = GPIO_Pin_11;` : 

=> 4번 릴레이 모듈에 신호가 들어올 경우( 9번 핀 활성화 ) 오른쪽 바퀴가 앞으로 간다.

**Comment by June222** [comment]
릴레이 모듈 네개 쓴 이유
-> 오른쪽 바퀴는 앞으로 왼쪽 바퀴는 뒤로 돌게 하는 식으로 구현하기 위해서이다.

**Comment by YeoJiSu** [comment]
# 실험 진행 과정

## 10.8
- [x] [전체 회의](https://github.com/June222/Embedded_System_Experiment_And_Design/issues/23) - 실험 주제 선정

## 10.9 - 10.12
- [x] [프로젝트 제안서](https://docs.google.com/document/d/1OQdf6bLrKx1HOgTaTaIeahLVXZgh8Sp4xe4YR7WCDkE/edit?usp=sharing) 작성
담당자: @chaeso36, @Tigerfriend1 

## 11.16 - 11.18
- [x] 프로젝트 세부 계획 설계에 대한 아이디어 구상
- [x] 자료 조사 

## 11.19
- [x] [전체 회의](https://github.com/YeoJiSu/Avoiding_Obstacles_Robot/issues/1#issuecomment-1320891514) - 하드웨어, 소프트웨어 구현에 대한 아이디어 통합

## 11.23
- [x] SW:  PC <-> 블루투스 간 통신 
담당자: @chaeso36, @June222  
- [x] SW: 장애물 피하기 알고리즘 초안 작성
담당자: @June222, @YeoJiSu  
- [x] HW: 로봇 제작 및 릴레이 모듈에 대한 실험
담당자: @Tigerfriend1, @chaeso36

## 11.29
- [x] [장애물 회피 알고리즘 고안](https://github.com/YeoJiSu/Avoiding_Obstacles_Robot/issues/2#issue-1461763509)
- [x] 예시 시나리오에 대한 [obstacle.c](https://github.com/YeoJiSu/Avoiding_Obstacles_Robot/blob/main/obstacle.c) 작성
담당자: @June222, @YeoJiSu  

## 11.30
- [x] SW: 릴레이 모듈 [] (https://github.com/YeoJiSu/Avoiding_Obstacles_Robot/blob/main/AvodingObstaclesRobot/user/main.c)
- [x] HW: 네가지 릴레이 모듈
